[template]
src   = "sites.html.tmpl"
dest  = "/usr/share/nginx/html/assets/sites.html"
keys  = [
         "/commerce/sfcc/enabled",
         "/commerce/hybris/enabled",
         "/commerce/wcs/enabled"
]
