version: "3.4"

# default environment variables for all spring-boot services
x-development-boot-envs:
  &development-boot-envs
  DEVELOPMENT_SETUP: "${DEVELOPMENT_SETUP:-false}"
  JAVA_DEBUG: "${JAVA_DEBUG:-false}"
  JAVA_DEBUG_SUSPEND: "${JAVA_DEBUG_SUSPEND:-false}"
  # enable entrypoint debugging i.e. set -x
  DEBUG_ENTRYPOINT: "${DEBUG_ENTRYPOINT:-false}"
  # writes heapdumps to /coremedia/heapdumps on oom exceptions. restart the container or mount a volume to
  # that directory to inspect the heapdumps
  HEAP_DUMP_ON_OOM: "${HEAP_DUMP_ON_OOM:-true}"

# default logging configuration
x-logging:
  &default-logging
  options:
    max-size: '12m'
    max-file: '5'
  driver: json-file

services:
  commerce-adapter-mock:
    image: ${COMMERCE_REPOSITORY_PREFIX:-coremedia}/commerce-adapter-mock:${COMMERCE_ADAPTER_MOCK_VERSION:-1.2.5}
    container_name: commerce-adapter-mock
    restart: always
    logging: *default-logging
    networks:
      - backend
    ports:
      - 44065:6565
      - 44081:8081
      - 44005:5005
    environment:
      << : *development-boot-envs
    labels:
      # this is a workaround to allow the ajax health check in the overview. Because the mock adapter is a
      # development only feature, we can define the labels here
      traefik.enable: "true"
      traefik.actuator.port: "8081"
      traefik.actuator.frontend.rule: Host:overview.${ENVIRONMENT_FQDN:-docker.localhost};PathPrefixStrip:/commerce-adapter-mock;AddPrefix:/actuator

  studio-server:
    environment:
      COMMERCE_HUB_DATA_ENDPOINTS_MOCK: ${COMMERCE_HUB_DATA_ENDPOINTS_MOCK:-commerce-adapter-mock:6565}
  cae-preview:
    environment:
      COMMERCE_HUB_DATA_ENDPOINTS_MOCK: ${COMMERCE_HUB_DATA_ENDPOINTS_MOCK:-commerce-adapter-mock:6565}
  cae-live:
    environment:
      COMMERCE_HUB_DATA_ENDPOINTS_MOCK: ${COMMERCE_HUB_DATA_ENDPOINTS_MOCK:-commerce-adapter-mock:6565}
  headless-server-preview:
    environment:
      COMMERCE_HUB_DATA_ENDPOINTS_MOCK: ${COMMERCE_HUB_DATA_ENDPOINTS_MOCK:-commerce-adapter-mock:6565}
  headless-server-live:
    environment:
      COMMERCE_HUB_DATA_ENDPOINTS_MOCK: ${COMMERCE_HUB_DATA_ENDPOINTS_MOCK:-commerce-adapter-mock:6565}
  overview:
    environment:
      COMMERCE_MOCK_ENABLED: "true"
