version: "3.4"

# default environment variables for all spring-boot services
x-development-boot-envs:
  &development-boot-envs
  DEVELOPMENT_SETUP: "${DEVELOPMENT_SETUP:-false}"
  JAVA_DEBUG: "${JAVA_DEBUG:-false}"
  JAVA_DEBUG_SUSPEND: "${JAVA_DEBUG_SUSPEND:-false}"
  # enable entrypoint debugging i.e. set -x
  DEBUG_ENTRYPOINT: "${DEBUG_ENTRYPOINT:-false}"

# default logging configuration
x-logging:
  &default-logging
  options:
    max-size: '12m'
    max-file: '5'
  driver: json-file

services:
  commerce-adapter-sfcc:
    image: ${COMMERCE_REPOSITORY_PREFIX:-coremedia}/commerce-adapter-sfcc:${COMMERCE_ADAPTER_SFCC_VERSION:-1.1.7}
    container_name: commerce-adapter-sfcc
    restart: always
    logging: *default-logging
    networks:
      - backend
    ports:
      - 44165:6565
      - 44181:8081
      - 44105:5005
    environment:
      << : *development-boot-envs
      SFCC_OCAPI_HOST: ${SFCC_OCAPI_HOST}
      SFCC_OCAPI_SANDBOX: ${SFCC_OCAPI_SANDBOX}
      SFCC_OAUTH_CLIENTID: ${SFCC_OAUTH_CLIENTID}
      SFCC_OAUTH_CLIENTPASSWORD: ${SFCC_OAUTH_CLIENTPASSWORD}
      SFCC_LINK_STOREFRONT_HOST: ${SFCC_LINK_STOREFRONT_HOST}
      SFCC_LINK_STOREFRONT_URL: ${SFCC_LINK_STOREFRONT_URL}
      MANAGEMENT_HEALTH_CATALOGS_ENABLED: ${MANAGEMENT_HEALTH_CATALOGS_ENABLED:-true}
      MANAGEMENT_HEALTH_STORES_ENABLED: ${MANAGEMENT_HEALTH_STORES_ENABLED:-true}

  studio-server:
    environment:
      COMMERCE_HUB_DATA_ENDPOINTS_SFCC: ${COMMERCE_HUB_DATA_ENDPOINTS_SFCC:-commerce-adapter-sfcc:6565}
  cae-preview:
    environment:
      COMMERCE_HUB_DATA_ENDPOINTS_SFCC: ${COMMERCE_HUB_DATA_ENDPOINTS_SFCC:-commerce-adapter-sfcc:6565}
  cae-live:
    environment:
      COMMERCE_HUB_DATA_ENDPOINTS_SFCC: ${COMMERCE_HUB_DATA_ENDPOINTS_SFCC:-commerce-adapter-sfcc:6565}
  headless-server-preview:
    environment:
      COMMERCE_HUB_DATA_ENDPOINTS_SFCC: ${COMMERCE_HUB_DATA_ENDPOINTS_SFCC:-commerce-adapter-sfcc:6565}
  headless-server-live:
    environment:
      COMMERCE_HUB_DATA_ENDPOINTS_SFCC: ${COMMERCE_HUB_DATA_ENDPOINTS_SFCC:-commerce-adapter-sfcc:6565}
