
version: "3.4"

services:
  hybris-proxy:
    image: ${REPOSITORY_PREFIX:-coremedia}/hybris-proxy
    container_name: hybris-proxy
    restart: always
    logging:
      driver: json-file
      options:
        max-size: "5m"
        max-file: "3"
    build:
      context: ../commerce-proxy
    networks:
      - backend
    environment:
      COMMERCE_SYSTEM: hybris
      ENVIRONMENT_FQDN: ${ENVIRONMENT_FQDN:-docker.localhost}
      HYBRIS_HOST: ${HYBRIS_HOST}
    labels:
      traefik.enable: "true"
      traefik.port: "80"
      traefik.frontend.entryPoints: http,https
      # this makes sure the apache sees the virtualhost of the traefik and can find the right handler
      traefik.frontend.passHostHeader: "true"
      traefik.frontend.headers.SSLRedirect: "true"
      traefik.shop-hybris.frontend.rule: Host:shop-hybris.${ENVIRONMENT_FQDN:-docker.localhost}
      traefik.shop-preview.frontend.rule: Host:shop-preview-hybris.${ENVIRONMENT_FQDN:-docker.localhost}
      # candy rulez!!!
      traefik.candy-shop-preview.frontend.rule: Host:candy-shop-preview-hybris.${ENVIRONMENT_FQDN:-docker.localhost}
      traefik.candy-shop.frontend.rule: Host:candy-shop-hybris.${ENVIRONMENT_FQDN:-docker.localhost}

  cae-preview:
    labels:
      traefik.hybris-servlets.frontend.rule: Host:preview.${ENVIRONMENT_FQDN:-docker.localhost};PathPrefix:/assets,/dynamic,/service,/resource,/catalogimage;AddPrefix:/blueprint/servlet

  cae-live:
    labels:
      traefik.hybris-servlets.frontend.rule: Host:apparel.${ENVIRONMENT_FQDN:-docker.localhost};PathPrefix:/assets,/dynamic,/service,/resource,/catalogimage;AddPrefix:/blueprint/servlet

  commerce-adapter-hybris:
    labels:
      traefik.enable: "true"
      traefik.actuator.port: "8081"
      traefik.actuator.frontend.rule: Host:overview.${ENVIRONMENT_FQDN:-docker.localhost};PathPrefixStrip:/commerce-adapter-hybris;AddPrefix:/actuator

  overview:
    environment:
      COMMERCE_HYBRIS_ENABLED: "true"
      COMMERCE_HYBRIS_HOST: ${HYBRIS_HOST}
